import glpiApi from '../index.js'

describe('glpiApi', () => {
  it('should exist all methods of "javascript-library-glpi"', () => {
    expect(glpiApi).toBeDefined()
    expect(glpiApi._parser).toBeDefined()
    expect(glpiApi._makeRequest).toBeDefined()
    expect(glpiApi.initSessionByCredentials).toBeDefined()
    expect(glpiApi.initSessionByUserToken).toBeDefined()
    expect(glpiApi.killSession).toBeDefined()
    expect(glpiApi.addItem).toBeDefined()
    expect(glpiApi.getFullSession).toBeDefined()
    expect(glpiApi.getActiveProfile).toBeDefined()
    expect(glpiApi.getMyProfiles).toBeDefined()
    expect(glpiApi.getMyEntities).toBeDefined()
    expect(glpiApi.getActiveEntities).toBeDefined()
    expect(glpiApi.getGlpiConfig).toBeDefined()
    expect(glpiApi.getAllItems).toBeDefined()
    expect(glpiApi.getAnItem).toBeDefined()
    expect(glpiApi.getSubItems).toBeDefined()
    expect(glpiApi.deleteItem).toBeDefined()
    expect(glpiApi.updateItem).toBeDefined()
    expect(glpiApi.changeActiveEntities).toBeDefined()
    expect(glpiApi.changeActiveProfile).toBeDefined()
    expect(glpiApi.getMultipleItems).toBeDefined()
    expect(glpiApi.searchItems).toBeDefined()
    expect(glpiApi.searchAllItems).toBeDefined()
    expect(glpiApi.listSearchOptions).toBeDefined()
    expect(glpiApi.registerUser).toBeDefined()
    expect(glpiApi.login).toBeDefined()
    expect(glpiApi.getUsers).toBeDefined()
    expect(glpiApi.updateEmails).toBeDefined()
    expect(glpiApi.genericRequest).toBeDefined()
    expect(glpiApi.uploadFile).toBeDefined()
  })
})