const CHANGE_LOADING = 'CHANGE_LOADING' // TODO: REFACTOR: CHECK USELESS ACTION TYPES
const CHANGE_USERNAME = 'CHANGE_USERNAME'
const CHANGE_EMAIL = 'CHANGE_EMAIL'
const FAILURE = 'FAILURE'
const CHANGE_ENDPOINT = 'CHANGE_ENDPOINT'
const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
const CHANGE_NOTIFICATION_MESSAGE = 'CHANGE_NOTIFICATION_MESSAGE'
const CHANGE_CURRENT_USER = 'CHANGE_CURRENT_USER'