// Authentication Actions Types

export const AUTH_START = 'AUTH_START'
export const AUTH_FINISH = 'AUTH_FINISH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_REFRESH_CAPTCHA = 'AUTH_REFRESH_CAPTCHA'
export const CHANGE_NOTIFICATION_MESSAGE = 'CHANGE_NOTIFICATION_MESSAGE'
export const FETCH_SIGNIN = 'FETCH_SIGNIN'
export const CHANGE_PASSWORD_CONFIGURATION = 'CHANGE_PASSWORD_CONFIGURATION'
export const LOGOUT = 'LOGOUT'
