// Authentication Actions Types

export const CHANGE_USERNAME = 'CHANGE_USERNAME'
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const CHANGE_CURRENT_USER = 'CHANGE_CURRENT_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CHANGE_NOTIFICATION_MESSAGE = 'CHANGE_NOTIFICATION_MESSAGE'