// ui Actions Types

export const CHANGE_NOTIFICATION_MESSAGE = 'CHANGE_NOTIFICATION_MESSAGE'
export const UI_TRANSACTION_START = 'UI_TRANSACTION_START'
export const UI_TRANSACTION_FINISH = 'UI_TRANSACTION_FINISH'
export const UI_TRANSACTION_FAIL = 'UI_TRANSACTION_FAIL'